### ISSUE TITLE
astext function fails to catch UnicodeDecodeError

### ISSUE THREAD

**Issue by JesseBowling** [bunzen/RashlyOutlaid#3]
Here's a sample:

`>>> from RashlyOutlaid.libwhois import ASNWhois
>>> asnwhois = ASNWhois()
>>> asnwhois.query = [ "191.114.98.53" ]
>>> asnwhois.result
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/RashlyOutlaid/libwhois.py", line 101, in get_result
    self._perform_query()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/RashlyOutlaid/libwhois.py", line 148, in _perform_query
    self._query_multiple()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/RashlyOutlaid/libwhois.py", line 176, in _query_multiple
    self.read()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/RashlyOutlaid/libwhois.py", line 86, in read
    self.buffer += astext(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/RashlyOutlaid/libwhois.py", line 50, in astext
    return data.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 45: invalid continuation byte
`
Obviously a try/catch would be ideal here, but unsure of best way to handle this...Working on a PR, but you may be more familiar with this type of text conversion issue.

**Comment by bunzen** [comment]
Fixed by JesseBowling in PR (thanks!) . Released new version (0.11.1) on pypi.
